apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddonTemplate
metadata:
  name: hello-test
spec:
  addonName: hello
  agentManifests:
    - kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: helloworld-agent
        namespace: {{ INSTALL_NAMESPACE }} # built-in INSTALL_NAMESPACE
        labels:
          app: helloworld-agent
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: helloworld-agent
        template:
          metadata:
            labels:
              app: helloworld-agent
          spec:
            serviceAccountName: helloworld-agent-sa
            containers:
              - name: helloworld-agent
                image: quay.io/test/helloworld:v2
                imagePullPolicy: IfNotPresent
                args:
                  - "/helloworld"
                  - "agent"
                  - "--test={{ FOO }}" # addonDeploymentConfig variables
    - kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: helloworld-agent-sa
        namespace: {{ INSTALL_NAMESPACE }}
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: helloworld-agent
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: helloworld-agent-sa
          namespace: {{ INSTALL_NAMESPACE }}
  registration:
    # kubeClient or custom signer, if kubeClient, user and group is in a certain format.
    # user is system:open-cluster-management:cluster:...
    # group is [system:open-cluster-management:cluster:, ...]
    - type: KubeClient
      kubeClient:
        permission:
          - type: CurrentCluster
            roleRef: cm-creator
          - type: SingleNamespace
            roleRef: cm-reader
            singleNamespace:
              namespace: open-cluster-management
    - type: CustomSigner
      customSigner:
        signerName: signer1
        subject:
          user: user1
          group:
            - g1
            - g2
          organizationUnit:
            - o1
            - o2
        signingCA:
          namespace: default
          name: ca-secret
