apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: hello
spec:
  addOnMeta:
    description: hello
    displayName: hello
  defaultConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      name: hello-test
    - group: addon.open-cluster-management.io/v1alpha1
      resource: addondeploymentconfig
      name: hello-test
      namespace: cluster1
