apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: hello-template
  namespace: cluster1
spec:
  installNamespace: open-cluster-management-agent-addon
#  config:
#    - group: addon.open-cluster-management.io
#      resource: addontemplates
#      name: hello-template
status:
  configReferences:
  - group: addon.open-cluster-management.io
    resource: addontemplates
    name: hello-template #Deprecated
    desiredConfig:
      name: hello-template
      specHash: yyy
    lastAppliedConfig:
      name: hello-template
      specHash: ""
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
    name: hello-template #Deprecated
    namespace: cluster1 #Deprecated
    desiredConfig:
      name: hello-template
      namespace: cluster1
      specHash: ccc
    lastAppliedConfig:
      name: hello-template
      namespace: cluster1
      specHash: ""
