apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-customer-ca
  namespace: open-cluster-management-hub
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
    resourceNames:
      - ca-secret
