apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: hello-template-v2
spec:
  addonName: hello-template
  agentManifests:
    - kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: hello-template-agent
        namespace: '{{INSTALL_NAMESPACE}}' # built-in INSTALL_NAMESPACE
        labels:
          app: hello-template-agent
          addon-template-version: v2
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: hello-template-agent
        template:
          metadata:
            labels:
              app: hello-template-agent
              addon-template-version: v2
          spec:
            serviceAccountName: hello-template-agent-sa
            containers:
              - name: helloworld-agent
                image: quay.io/zhujian/addon-examples:latest
                imagePullPolicy: Always
                args:
                  - "/helloworld"
                  - "agent"
                  - "--cluster-name={{CLUSTER_NAME}}"
                  - "--addon-namespace={{INSTALL_NAMESPACE}}"
                  - "--addon-name=hello-template"
                  - "--hub-kubeconfig={{HUB_KUBECONFIG}}"
                  - "--v={{LOG_LEVEL}}" # addonDeploymentConfig variables
    - kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: hello-template-agent-sa
        namespace: "{{INSTALL_NAMESPACE}}"
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: hello-template-agent
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: hello-template-agent-sa
          namespace: "{{INSTALL_NAMESPACE}}"
  registration:
    - type: KubeClient
      kubeClient:
        hubPermissions:
          - type: CurrentCluster
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cm-admin
          - type: SingleNamespace
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: Role
              name: cm-reader
            singleNamespace:
              namespace: open-cluster-management
    - type: CustomSigner
      customSigner:
        signerName: example.com/signer-name
        subject:
          user: user1
          groups:
            - g1
            - g2
          organizationUnit:
            - o1
            - o2
        signingCA:
          namespace: default
          name: ca-secret
